excerpt_separator: ""
pygments: rouge
markdown: kramdown
url: http://shepherdonline.github.io/ShepherdMapleSyrupFestival/
title: Shepherd Maple Syrup Festival
tagline: A log of everyday life
description: My awesome new site
paginate: 5

theme: jekyll-theme-minimal
